----- normal table
CREATE TABLE T_ORDER(
    ID NUMBER,
    CREATOR VARCHAR2(32),
    CDATE DATE,
    EDITOR VARCHAR2(32),
    EDATE DATE,
    CONSTRAINT PK_ORDER PRIMARY KEY (ID),
);


----- partition table