ALTER TABLE T_ORDER_000 ADD CONSTRAINT UK_ORDER_000_ORDER_NBR UNIQUE (ORDER_NBR);

ALTER TABLE T_ORDER_000 ADD CONSTRAINT IDX_ORDER_000_CDATE INDEX (CDATE);

ALTER TABLE T_ORDER_000 ADD CONSTRAINT UK_ORDER_000_KEY KEY (KEY);

-- in mysql, not null is not a constraint, so no constraint name for not null
ALTER TABLE T_ORDER_000 MODIFY ORDER_NBR NOT NULL;

ALTER TABLE T_ORDER_000 CHANGE ORDER_NBR CDATE NOT NULL;
