------------------------------
----- simple table
------------------------------
create table T_ORDER_000 (
	ID BIGINT NOT NULL,
	ORDER_NBR VARCHAR(32) NOT NULL,
	CDATE DATETIME,
	PRIMARY KEY (ID)
);

create table T_ORDER_TYPE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TYPE_CODE VARCHAR(32),
	CDATE DATETIME,
	PRIMARY KEY (ID)
);
------------------------------
----- partition table
----- check whether supports?
----- show variables like '%partition%';
------------------------------
-- range partition
CREATE TABLE T_ORDER_RANGE_000(
    ID BIGINT PRIMARY KEY,
    CDATE DATETIME
)
PARTITION BY RANGE(YEAR(CDATE)) (
    PARTITION TP_ORDER_2007 VALUES LESS THAN(2008),
    PARTITION TP_ORDER_2008 VALUES LESS THAN(2009) -- MAXVALUE
);

-- list partition
CREATE TABLE T_ORDER_LIST_000(
    ID BIGINT PRIMARY KEY,
    CDATE DATETIME,
    MONTH INT
)
PARTITION BY LIST(MONTH) (
    PARTITION TP_ORDER_000_M01 VALUES IN (01),
    PARTITION TP_ORDER_000_M02 VALUES IN (02),
    PARTITION TP_ORDER_000_M03 VALUES IN (03),
    PARTITION TP_ORDER_000_M04 VALUES IN (04),
    PARTITION TP_ORDER_000_M05 VALUES IN (05),
    PARTITION TP_ORDER_000_M06 VALUES IN (06),
    PARTITION TP_ORDER_000_M07 VALUES IN (07),
    PARTITION TP_ORDER_000_M08 VALUES IN (08),
    PARTITION TP_ORDER_000_M09 VALUES IN (09),
    PARTITION TP_ORDER_000_M10 VALUES IN (10),
    PARTITION TP_ORDER_000_M11 VALUES IN (11),
    PARTITION TP_ORDER_000_M12 VALUES IN (12)
);

-- hash partition
CREATE TABLE T_ORDER_HASH_000(
    ID BIGINT PRIMARY KEY,
    CDATE DATETIME
)
PARTITION BY HASH(ID) PARTITIONS 32;

-- key partition
CREATE TABLE T_ORDER_KEY_000 (
    ID BIGINT,
    CDATE DATETIME,
    PRIMARY KEY (ID)
)
PARTITION BY KEY(ID) PARTITIONS 5;

------------------------------
----- alter table
------------------------------
ALTER TABLE T_ORDER_000 AUTO_INCREMENT = 10;
